name: dart_lens
description: An intuitive and powerful tool for exploring and managing Dart and Flutter projects.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0

  # state management
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.6
  fast_immutable_collections: ^9.0.0

  path: ^1.8.2
  file_picker: ^5.2.6

  url_launcher: ^6.1.10

  # UI
  google_fonts: ^4.0.3
  flex_color_scheme: ^6.1.2
  flex_seed_scheme: ^1.2.2
  flextras: ^1.0.0
  cupertino_icons: ^1.0.5

  analyzer: ^5.7.1

  pub_semver: ^2.1.3
  pubspec_parse: ^1.2.2
  pub_api_client: # ^2.4.0
    git:
      url: https://github.com/fluttertools/pub_api_client.git
      ref: 10e90ad7436843a1cb224a477e22fda35be5cd77

  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2

  very_good_analysis: ^4.0.0+1

  package_rename: ^1.1.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter pub run package_rename:set
package_rename_config:
  macos:
    app_name: DartLens
    package_name: app.dartlens
    copyright_notice: Copyright © 2023 dartlens.app. All rights reserved.

  windows:
    app_name: DartLens
    organization: dartlens.app
    copyright_notice: Copyright © 2023 dartlens.app. All rights reserved.
    exe_name: DartLens

  linux:
    app_name: DartLens
    package_name: app.dartlens
    exe_name: DartLens
