name: dart_lens
description: An intuitive and powerful tool for exploring and managing Dart and Flutter projects.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1

  # state management
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.6
  fast_immutable_collections: ^9.1.5

  path: ^1.8.2
  file_picker: ^5.3.2

  # UI
  google_fonts: ^4.0.4
  flex_color_scheme: ^7.1.2
  flex_seed_scheme: ^1.3.0
  flextras: ^1.0.0
  cupertino_icons: ^1.0.5

  analyzer: ^5.13.0

  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  pub_api_client: # ^2.4.0
    git:
      url: https://github.com/fluttertools/pub_api_client.git
      ref: 10e90ad7436843a1cb224a477e22fda35be5cd77

  clipboard: ^0.1.3
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  send_support_email:
    git:
      url: https://github.com/albemala/send_support_email.git
      ref: ebef0be4dbaa0795216435dd636fc05b2db6979d

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  freezed: ^2.3.5

  very_good_analysis: ^5.0.0+1

  package_rename: ^1.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# dart run package_rename
package_rename_config:
  macos:
    app_name: DartLens
    package_name: app.dartlens
    copyright_notice: Copyright © 2023 dartlens.app. All rights reserved.

  windows:
    app_name: DartLens
    organization: dartlens.app
    copyright_notice: Copyright © 2023 dartlens.app. All rights reserved.
    exe_name: DartLens

  linux:
    app_name: DartLens
    package_name: app.dartlens
    exe_name: DartLens
